/**
 * Build a campaign-planning Markdown document from a town_campaign_export payload.
 */

function clean(v) {
  if (v == null) return '';
  return String(v).replace(/\r\n/g, '\n').trim();
}

function line(label, value) {
  const v = clean(value);
  return v ? `- **${label}:** ${v}` : '';
}

function push(lines, ...parts) {
  for (const p of parts) {
    if (p == null || p === '') continue;
    if (Array.isArray(p)) push(lines, ...p);
    else lines.push(p);
  }
}

function parseMaybeJson(raw) {
  if (raw == null || raw === '') return null;
  if (typeof raw === 'object') return raw;
  try {
    return JSON.parse(raw);
  } catch {
    return raw;
  }
}

function formatMeta(meta = {}) {
  const lines = [];
  const keys = [
    ['biome', 'Biome'],
    ['settlement_type', 'Settlement type'],
    ['difficulty_level', 'Difficulty'],
    ['weather_year', 'Weather year'],
    ['macro_food_supply', 'Food supply index'],
    ['sim_rolling_summary', 'Rolling simulation summary'],
  ];
  for (const [k, label] of keys) {
    if (meta[k]) lines.push(line(label, meta[k]));
  }
  const demo = parseMaybeJson(meta.demographics);
  if (Array.isArray(demo) && demo.length) {
    lines.push('- **Demographics:**');
    for (const d of demo) {
      const race = d.race || d.name || 'Unknown';
      const pct = d.pct != null ? d.pct : d.percent;
      lines.push(`  - ${race}${pct != null ? ` — ${pct}%` : ''}`);
    }
  } else if (typeof demo === 'string' && demo) {
    lines.push(line('Demographics', demo));
  }
  const gen = parseMaybeJson(meta.gen_rules);
  if (gen && typeof gen === 'object') {
    const bits = [];
    if (gen.intake_level != null) bits.push(`intake level ${gen.intake_level}`);
    if (gen.max_level != null) bits.push(`max level ${gen.max_level}`);
    if (gen.hp_rule) bits.push(`HP ${gen.hp_rule}`);
    if (gen.name_style) bits.push(`names: ${gen.name_style}`);
    if (bits.length) lines.push(line('Generation rules', bits.join('; ')));
  }
  return lines;
}

function formatCharacter(c) {
  const lines = [];
  const title = [c.name, c.title ? `(${c.title})` : ''].filter(Boolean).join(' ');
  lines.push(`#### ${title || 'Unnamed'}`);
  const header = [
    c.race,
    c.class,
    c.level != null ? `Lvl ${c.level}` : '',
    c.alignment,
    c.status,
  ].filter(Boolean).join(' · ');
  if (header) lines.push(header);
  push(lines,
    line('Role', c.role),
    line('Age / gender', [c.age, c.gender].filter(Boolean).join(', ')),
    line('Spouse', c.spouse && c.spouse !== 'None' ? `${c.spouse}${c.spouse_label ? ` (${c.spouse_label})` : ''}` : ''),
    line('HP / AC', [c.hp != null ? `HP ${c.hp}` : '', c.ac ? `AC ${c.ac}` : ''].filter(Boolean).join(', ')),
    line('Abilities', ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA']
      .map((ab) => {
        const key = ab === 'INT' ? 'int_' : ab.toLowerCase();
        return c[key] != null && c[key] !== '' ? `${ab} ${c[key]}` : null;
      })
      .filter(Boolean)
      .join(', ')),
    line('Saves', c.saves),
    line('Attack', c.atk),
    line('Languages', c.languages),
    line('Feats', c.feats),
    line('Skills', c.skills_feats),
    line('Domains', c.domains),
    line('Gear', c.gear),
  );
  if (clean(c.history)) {
    lines.push('');
    lines.push('**Biography / history**');
    lines.push(clean(c.history));
  }
  if (clean(c.memory_summary)) {
    lines.push('');
    lines.push('**Memory summary**');
    lines.push(clean(c.memory_summary));
  }
  const memories = c.memories || [];
  if (memories.length) {
    lines.push('');
    lines.push('**Memories**');
    for (const m of memories.slice(0, 25)) {
      const tag = [m.memory_type, m.game_date, m.importance != null ? `imp ${m.importance}` : '']
        .filter(Boolean).join(', ');
      lines.push(`- (${tag}) ${clean(m.content)}`);
    }
  }
  const equipment = c.equipment || [];
  if (equipment.length) {
    lines.push('');
    lines.push('**Equipment**');
    for (const e of equipment) {
      const eq = Number(e.equipped) ? 'equipped' : 'stowed';
      const qty = e.quantity > 1 ? ` ×${e.quantity}` : '';
      lines.push(`- ${e.item_name}${qty} (${eq}${e.slot ? `, ${e.slot}` : ''})`);
    }
  }
  lines.push('');
  return lines;
}

/**
 * @param {object} payload - town_campaign_export response
 * @returns {string}
 */
export function formatTownExportMarkdown(payload) {
  const lines = [];
  const town = payload.town || {};
  const campaign = payload.campaign || {};
  const cal = payload.calendar;
  const rules = payload.campaign_rules || {};
  const social = town.social || {};

  lines.push(`# Town Docket: ${town.name || 'Unnamed Town'}`);
  if (town.subtitle) lines.push(`*${clean(town.subtitle)}*`);
  lines.push('');
  lines.push(`> Generated by Eon Weaver for campaign planning / AI briefing.`);
  lines.push(`> Exported: ${payload.generated_at || new Date().toISOString()}`);
  lines.push(`> Format: \`${payload.format || 'eonweaver.town_campaign_export.v1'}\``);
  lines.push('');

  lines.push('## Campaign context');
  push(lines,
    line('Campaign', campaign.name),
    line('Edition', campaign.dnd_edition),
    line('Campaign description', campaign.description),
  );
  if (cal) {
    const monthNames = Array.isArray(cal.month_names) ? cal.month_names : [];
    const monthLabel = monthNames[(Number(cal.current_month) || 1) - 1] || `Month ${cal.current_month}`;
    lines.push(line('Current date', `${cal.current_day} ${monthLabel} ${cal.current_year}${cal.era_name ? ` ${cal.era_name}` : ''}`));
  }
  if (clean(rules.campaign_description)) {
    lines.push('');
    lines.push('### Campaign primer');
    lines.push(clean(rules.campaign_description));
  }
  if (clean(rules.rules_text)) {
    lines.push('');
    lines.push('### House rules / lore notes');
    lines.push(clean(rules.rules_text));
  }
  lines.push('');

  lines.push('## Town overview');
  push(lines,
    line('Party base', town.is_party_base ? 'yes' : 'no'),
    line('Encounter town', town.is_encounter_town ? 'yes' : 'no'),
    ...formatMeta(town.meta || {}),
  );
  const pins = town.world_map_locations || [];
  if (pins.length) {
    lines.push('- **World map pin(s):**');
    for (const p of pins) {
      lines.push(`  - ${p.location_name || town.name} @ ${p.x_pct}%, ${p.y_pct}%`);
    }
  }
  lines.push('');

  const history = town.history || [];
  lines.push('## Town history');
  if (!history.length) {
    lines.push('_No history entries._');
  } else {
    const ordered = [...history].sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
    for (const h of ordered) {
      lines.push(`### ${clean(h.heading) || 'Untitled'}`);
      lines.push(clean(h.content) || '_Empty entry._');
      lines.push('');
    }
  }
  lines.push('');

  const buildings = town.buildings || [];
  lines.push('## Places (buildings & rooms)');
  if (!buildings.length) {
    lines.push('_No buildings recorded._');
  } else {
    for (const b of buildings) {
      lines.push(`### ${b.name || 'Unnamed building'}`);
      push(lines,
        line('Type / status', [b.building_type, b.status].filter(Boolean).join(' · ')),
        line('Owner', b.owner_name),
        line('Description', b.description),
      );
      const residents = b.residents || [];
      if (residents.length) {
        lines.push(`- **Residents:** ${residents.map((r) => r.name).join(', ')}`);
      }
      const rooms = b.rooms || [];
      if (rooms.length) {
        lines.push('- **Rooms:**');
        for (const r of rooms) {
          lines.push(`  - **${r.name}** (${r.room_type || 'room'})${r.description ? ` — ${clean(r.description)}` : ''}`);
        }
      }
      lines.push('');
    }
  }
  lines.push('');

  const factions = social.factions || [];
  lines.push('## Factions');
  if (!factions.length) {
    lines.push('_No factions._');
  } else {
    for (const f of factions) {
      lines.push(`### ${f.name}`);
      push(lines,
        line('Type / alignment', [f.faction_type, f.alignment, f.disposition].filter(Boolean).join(' · ')),
        line('Status / influence', [f.status, f.influence != null ? `influence ${f.influence}` : ''].filter(Boolean).join(' · ')),
        line('Public goal', f.public_goal),
        line('Secret goal', f.secret_goal),
        line('Description', f.description || f.notes),
      );
      const members = f.members || [];
      if (members.length) {
        lines.push('- **Members:**');
        for (const m of members) {
          lines.push(`  - ${m.character_name}${m.role ? ` — ${m.role}` : ''}${m.loyalty != null ? ` (loyalty ${m.loyalty})` : ''}`);
        }
      }
      const rels = f.relations || [];
      if (rels.length) {
        lines.push('- **Relations:**');
        for (const r of rels) {
          lines.push(`  - vs ${r.target_name}: disposition ${r.disposition}${r.reason ? ` — ${r.reason}` : ''}`);
        }
      }
      lines.push('');
    }
  }
  lines.push('');

  const incidents = social.incidents || [];
  lines.push('## Incidents & plot hooks');
  if (!incidents.length) {
    lines.push('_No incidents._');
  } else {
    for (const inc of incidents) {
      lines.push(`### [${inc.status || 'active'}] ${clean(inc.summary).slice(0, 120) || 'Incident'}`);
      push(lines,
        line('Type / severity', [inc.incident_type, inc.severity != null ? `sev ${inc.severity}` : ''].filter(Boolean).join(' · ')),
        line('Motive', inc.motive),
        line('Game date', inc.game_date),
        line('Evidence', inc.evidence_found),
        line('DM notes', inc.dm_notes),
      );
      const parts = inc.participants || [];
      if (parts.length) {
        lines.push('- **Participants:**');
        for (const p of parts) {
          lines.push(`  - ${p.character_name} — ${p.role || 'involved'}${p.knows_truth ? ' (knows truth)' : ''}${p.alibi ? `; alibi: ${p.alibi}` : ''}`);
        }
      }
      const clues = inc.clues || [];
      if (clues.length) {
        lines.push('- **Clues:**');
        for (const c of clues) {
          const flags = [
            Number(c.found) ? 'found' : 'hidden',
            Number(c.red_herring) ? 'red herring' : '',
            c.location || '',
          ].filter(Boolean).join(', ');
          lines.push(`  - (${flags}) ${clean(c.clue_text)}`);
        }
      }
      lines.push('');
    }
  }
  lines.push('');

  const reputation = social.reputation || [];
  if (reputation.length) {
    lines.push('## Party reputation');
    for (const r of reputation) {
      lines.push(`- **${r.pc_name}:** disposition ${r.disposition}${r.reason ? ` — ${r.reason}` : ''}`);
    }
    lines.push('');
  }

  const relationships = social.relationships || [];
  if (relationships.length) {
    lines.push('## Relationships');
    for (const r of relationships) {
      lines.push(`- ${r.char1_name} ↔ ${r.char2_name}: ${r.rel_type || 'linked'} (disp ${r.disposition})${r.reason ? ` — ${r.reason}` : ''}`);
    }
    lines.push('');
  }

  const characters = town.characters || [];
  const living = characters.filter((c) => !c.status || /alive/i.test(c.status));
  const departed = characters.filter((c) => c.status && !/alive/i.test(c.status));
  lines.push('## Characters');
  lines.push(`_${living.length} living / ${departed.length} departed / ${characters.length} total_`);
  lines.push('');
  if (living.length) {
    lines.push('### Living residents');
    for (const c of living) push(lines, ...formatCharacter(c));
  }
  if (departed.length) {
    lines.push('### Departed / deceased');
    for (const c of departed) push(lines, ...formatCharacter(c));
  }
  lines.push('');

  const scribe = payload.scribe_library || [];
  lines.push('## Scribe library (quests / lore / notes)');
  if (!scribe.length) {
    lines.push('_No scribe entries for this town/campaign._');
  } else {
    for (const s of scribe) {
      lines.push(`### [${s.generator_type || 'note'}] ${s.title || 'Untitled'}`);
      lines.push(clean(s.body) || '_Empty._');
      lines.push('');
    }
  }
  lines.push('');

  const wiki = payload.wiki || [];
  lines.push('## Campaign wiki');
  if (!wiki.length) {
    lines.push('_No wiki articles._');
  } else {
    for (const w of wiki) {
      const tags = (w.tags || []).length ? ` _(tags: ${(w.tags || []).join(', ')})_` : '';
      lines.push(`### ${w.title || w.slug}${tags}`);
      lines.push(clean(w.body) || '_Empty._');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_End of town docket. Paste this Markdown into an AI chat, or use the PDF for table / binder use._');
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

/**
 * Suggested filename stem for downloads.
 * @param {object} payload
 */
export function townExportFilenameStem(payload) {
  const name = (payload?.town?.name || 'town')
    .replace(/[^\w\-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, 60) || 'town';
  const d = new Date();
  const stamp = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
  return `${name}_campaign_docket_${stamp}`;
}
